[package]
name = "audiagentic-secrets-memory-spike"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
audiagentic-foundation-sensitive-spike = { path = "../foundation-sensitive" }
audiagentic-secrets-api-spike = { path = "../secrets-api" }
async-trait.workspace = true

[dev-dependencies]
tokio.workspace = true
