[package]
name = "audiagentic-clean-workflow-bevy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
audiagentic-clean-capabilities = { path = "../capabilities", version = "0.1.0" }
bevy_app.workspace = true
bevy_ecs.workspace = true
tokio.workspace = true
