from __future__ import annotations

import argparse
import sys
from pathlib import Path

_here = Path(__file__).resolve()
for _candidate in [_here, *_here.parents]:
    if (_candidate / "src" / "audiagentic").is_dir() and (_candidate / "tests").is_dir():
        if str(_candidate / "src") not in sys.path:
            sys.path.insert(0, str(_candidate / "src"))
        break

from audiagentic.foundation.components.base import MODE_REQUIRED_MANAGED
from audiagentic.foundation.components.loader import register_all_components
from audiagentic.foundation.components.registry import all_descriptors
from audiagentic.paths import REPO_ROOT

MANAGED_MARKDOWN_HEADER = "<!-- MANAGED_BY_AUDIAGENTIC: do not edit directly. -->"


def _build_skill_surface_paths() -> list[str]:
    """Expand skill-surfaces config over canonical tags to get expected paths."""
    try:
        from audiagentic.execution.jobs.prompt_syntax import load_prompt_syntax
    except ImportError:
        return []
    syntax = load_prompt_syntax(REPO_ROOT)
    canonical_tags = syntax.get("canonical-tags") or []
    skill_surfaces = syntax.get("skill-surfaces") or {}
    paths: list[str] = []
    for _provider, config in skill_surfaces.items():
        path_template = config.get("path", "")
        if not path_template:
            continue
        for tag in canonical_tags:
            if isinstance(tag, str) and tag:
                paths.append(path_template.format(tag=tag).replace("\\", "/"))
    return paths


def _build_required_paths() -> list[str]:
    """Required paths = non-recursive required-managed files + skill surface paths.

    Recursive directories are checked for existence but NOT scanned file-by-file
    to avoid catching generated subdirectories (e.g. node_modules).
    """
    register_all_components()
    paths: list[str] = []

    for descriptor in all_descriptors().values():
        for cf in descriptor.files:
            if cf.lifecycle != MODE_REQUIRED_MANAGED:
                continue
            if not cf.recursive:
                paths.append(cf.rel_path.replace("\\", "/"))

    paths.extend(_build_skill_surface_paths())
    return sorted(set(paths))


def _build_managed_header_paths() -> list[str]:
    """Managed header check applies only to skill surface files generated by the renderer."""
    return sorted(set(_build_skill_surface_paths()))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Check managed baseline asset visibility.")
    parser.add_argument(
        "--check-gitignore",
        action="store_true",
        help="Verify that .gitignore excludes .audiagentic/runtime/.",
    )
    parser.add_argument(
        "--check-managed-headers",
        action="store_true",
        help="Verify that managed markdown surfaces carry the AUDiaGentic managed header.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    required_paths = _build_required_paths()

    issues = []
    missing = [p for p in required_paths if not (REPO_ROOT / p).exists()]
    if missing:
        issues.extend(f"missing required asset: {path}" for path in missing)

    runtime_root = REPO_ROOT / ".audiagentic" / "runtime"
    if not runtime_root.exists():
        issues.append("missing runtime root: .audiagentic/runtime")

    if args.check_gitignore:
        gitignore = REPO_ROOT / ".gitignore"
        if not gitignore.exists():
            issues.append("missing .gitignore")
        else:
            text = gitignore.read_text(encoding="utf-8")
            if ".audiagentic/runtime/" not in text.replace("\\", "/"):
                issues.append(".gitignore does not explicitly exclude .audiagentic/runtime/")

    if args.check_managed_headers:
        for rel_path in _build_managed_header_paths():
            path = REPO_ROOT / rel_path
            if not path.exists():
                issues.append(f"missing managed file for header check: {rel_path}")
                continue
            text = path.read_text(encoding="utf-8")
            if MANAGED_MARKDOWN_HEADER not in text:
                issues.append(f"managed header missing: {rel_path}")

    if issues:
        print("Baseline asset check failed:")
        for issue in issues:
            print(f"- {issue}")
        return 1

    print("Baseline asset check passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
