"""Provider-neutral agent transport protocols."""

from .acp import (
    AcpEvent,
    AcpLaunch,
    AcpResult,
    AcpSessionTransport,
    ProviderLaunch,
    run_acp_prompt,
)
from .agent_output import (
    AgentOutputEvent,
    AgentOutputKind,
    OutputSink,
)
from .agent_session import (
    AgentSessionTransport,
    ControlDisposition,
    CorrelationQuality,
    ObservationSink,
    SessionControlAction,
    SessionControlRequest,
    SessionControlResult,
    SessionFailureDisposition,
    SessionOpenResult,
    SessionPrompt,
    SessionTurnResult,
    TransportObservation,
    TransportObservationKind,
)
from .agent_status import (
    AgentLifecycle,
    AgentOutcome,
    AgentStatusDecisions,
    AgentStatusScope,
    AgentStatusSnapshot,
    AgentWaitReason,
    StatusEvidenceConfidence,
)
from .harness_status_observer import (
    StatusEvidence,
    StatusEvidenceSourceKind,
    StatusObserverLease,
    StatusObserverRequest,
    StatusObserverResult,
    StatusObserverState,
)
from .session_binding import (
    BindingRelation,
    ProviderSessionRef,
    SessionBindingIntent,
    SessionMappingCapabilities,
    SessionMappingCapability,
    SessionOwnership,
)
from .session_surface import (
    ContentChannelCapability,
    ContentChannelId,
    ContentStreamCapabilities,
    ControlSupport,
    LifecycleInstallation,
    LifecycleObservationCapabilities,
    LifecycleSource,
    PlatformEvidence,
    PreparedSessionTransport,
    ResolvedSessionSurface,
    SessionIdentityCapabilities,
    SessionIdentityOperation,
    SessionMappingFacts,
    SessionOwnershipMode,
    SessionSurfaceRef,
    SurfaceValidation,
    ValidationEvidence,
)

__all__ = [
    # ACP transport (AcpAgentSessionTransport is private to acp.py / provider adapters)
    "AcpEvent",
    "AcpLaunch",  # alias of ProviderLaunch, kept for the ACP subsystem
    "AcpResult",
    "AcpSessionTransport",
    "ProviderLaunch",
    "run_acp_prompt",
    # AS28 neutral agent-session contract
    "AgentSessionTransport",
    "ControlDisposition",
    "CorrelationQuality",
    "ObservationSink",
    "SessionControlAction",
    "SessionControlRequest",
    "SessionControlResult",
    "SessionFailureDisposition",
    "SessionOpenResult",
    "SessionPrompt",
    "SessionTurnResult",
    "TransportObservation",
    "TransportObservationKind",
    # AS29 session-surface value types
    "ControlSupport",
    "PreparedSessionTransport",
    "ContentChannelCapability",
    "ContentChannelId",
    "ContentStreamCapabilities",
    "LifecycleInstallation",
    "LifecycleObservationCapabilities",
    "LifecycleSource",
    "PlatformEvidence",
    "ResolvedSessionSurface",
    "SessionIdentityCapabilities",
    "SessionIdentityOperation",
    "SessionMappingFacts",
    "SessionOwnershipMode",
    "SessionSurfaceRef",
    "SurfaceValidation",
    "ValidationEvidence",
    # AS30 session-binding foundation contract
    "BindingRelation",
    "ProviderSessionRef",
    "SessionBindingIntent",
    "SessionMappingCapabilities",
    "SessionMappingCapability",
    "SessionOwnership",
    # AS31 agent-output foundation contract
    "AgentOutputEvent",
    "AgentOutputKind",
    "OutputSink",
    # AS19 status-observer foundation contract
    "StatusEvidence",
    "StatusEvidenceSourceKind",
    "StatusObserverLease",
    "StatusObserverRequest",
    "StatusObserverResult",
    "StatusObserverState",
    # AS37 agent-status projection contract
    "AgentOutcome",
    "AgentLifecycle",
    "AgentStatusDecisions",
    "AgentStatusScope",
    "AgentStatusSnapshot",
    "AgentWaitReason",
    "StatusEvidenceConfidence",
]
